"""Decomposed environment sub-package.

Re-exports all public constants from ``config`` so that consumers can
``from .env import MAP_SIZE`` etc.  The ``RobotCoverageEnv`` class itself
lives in the parent-level ``robot_env.py`` to avoid circular imports.
"""

from .config import (
    CELLS_MISSED_THRESHOLD,
    DT,
    HEADING_NOISE,
    MAP_SIZE,
    MAX_FIELD_ATTEMPTS,
    MAX_NON_NEW_STEPS,
    METERS_PER_PIXEL,
    NUM_MAPS,
    NUM_RAYS,
    OBSTACLE_DILATION,
    PHASE_WEIGHT_DECAY,
    PHASES,
    POSITION_NOISE,
    RAY_COLORS,
    RAY_MAX_DIST,
    REWARD_AREA_MAX,
    REWARD_AREA_SCALE,
    REWARD_BASE_PENALTY,
    REWARD_COLLISION,
    REWARD_TV_MAX,
    REWARD_TV_SCALE,
    ROBOT_RADIUS,
    ROBOT_RADIUS_PX,
    ROBOT_SIDE,
    ROBOT_SPEED_V,
    ROBOT_SPEED_W,
    SENSOR_DIM,
    SPAWN_SAFETY_RADIUS_PX,
    SUCCESS_THRESHOLD,
    SUCCESS_WINDOW,
    VIRTUAL_MARGIN_PX,
)

__all__ = [
    "CELLS_MISSED_THRESHOLD",
    "DT",
    "HEADING_NOISE",
    "MAP_SIZE",
    "MAX_FIELD_ATTEMPTS",
    "MAX_NON_NEW_STEPS",
    "METERS_PER_PIXEL",
    "NUM_MAPS",
    "NUM_RAYS",
    "OBSTACLE_DILATION",
    "PHASE_WEIGHT_DECAY",
    "PHASES",
    "POSITION_NOISE",
    "RAY_COLORS",
    "RAY_MAX_DIST",
    "REWARD_AREA_MAX",
    "REWARD_AREA_SCALE",
    "REWARD_BASE_PENALTY",
    "REWARD_COLLISION",
    "REWARD_TV_MAX",
    "REWARD_TV_SCALE",
    "ROBOT_RADIUS",
    "ROBOT_RADIUS_PX",
    "ROBOT_SIDE",
    "ROBOT_SPEED_V",
    "ROBOT_SPEED_W",
    "SENSOR_DIM",
    "SPAWN_SAFETY_RADIUS_PX",
    "SUCCESS_THRESHOLD",
    "SUCCESS_WINDOW",
    "VIRTUAL_MARGIN_PX",
]
